"""initial migrate

Revision ID: c5a7c7126ea4
Revises: b625abd59081
Create Date: 2025-04-16 20:47:39.242920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a7c7126ea4'
down_revision = 'b625abd59081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normal_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('is_trial_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_status', sa.Enum('TRIAL', 'ACTIVE', 'EXPIRED', 'BLOCKED', name='subscriptionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normal_users')
    # ### end Alembic commands ###
